apiVersion: v1
kind: Service
metadata:
  name: webapp-sql
spec:
  type: NodePort
  selector:
    app: webapp-sql
    tier: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-sql
      tier: frontend
  template:
    metadata:
      labels:
        app: webapp-sql
        tier: frontend
    spec:
      containers:
      - name: webapp1
        image: vishweshrushi/snake-game:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
