apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: snake-game-ingress
  namespace: app
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webapp-sql
            port:
              number: 80
